from collections.abc import Awaitable, Callable
from typing import Protocol

MessageHandler = Callable[[bytes], Awaitable[None]]
RpcHandler = Callable[[bytes], Awaitable[bytes]]


class BrokerPort(Protocol):
    async def connect(self, url: str) -> None: ...

    async def declare(self, queue: str) -> None: ...

    async def declare_retry_queue(self, queue: str, ttl_ms: int, dead_letter_to: str) -> None: ...

    async def publish(self, queue: str, body: bytes) -> None: ...

    async def consume(self, queue: str, handler: MessageHandler) -> None: ...

    async def rpc_call(self, queue: str, body: bytes) -> bytes: ...

    async def close(self) -> None: ...
