sonar.projectKey=sandrosmarzaro_resenhazord2
sonar.organization=sandrosmarzaro
sonar.projectName=resenhazord2

sonar.sources=bot,gateway/src
sonar.tests=tests,gateway/tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.typescript.lcov.reportPaths=gateway/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.venv/**