from typing import Protocol


class WhatsAppPort(Protocol):
    async def group_metadata(self, jid: str) -> dict: ...

    async def group_participants_update(
        self, jid: str, participants: list[str], action: str
    ) -> list[dict]: ...

    async def on_whatsapp(self, jids: list[str]) -> list[dict]: ...

    async def send_message(self, jid: str, content: dict, options: dict | None = None) -> dict: ...

    async def update_profile_picture(self, jid: str, image: bytes) -> None: ...

    async def group_update_subject(self, jid: str, subject: str) -> None: ...

    async def group_update_description(self, jid: str, description: str) -> None: ...

    async def send_presence_update(self, presence_type: str, jid: str) -> None: ...

    async def download_media(self, message_id: str, source: str) -> bytes: ...
